service: orders
provider:
  name: aws
  runtime: java11
  timeout: 60
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DeleteNetworkInterface'
      Resource: "*"
package:
  artifact: target/orders-original.jar
functions:
  orders:
    environment:
      DB_HOSTNAME: ${opt:hostname}
      DB_PASSWORD: ${opt:password}
    handler: works.weave.socks.orders.StreamLambdaHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    vpc:
      securityGroupIds:
        - "sg-056ee613e30cfa5b5"
      subnetIds:
        - "subnet-0af41f8e0404d7b23"
        - "subnet-0c2515119bdf77d4c"
    provisionedConcurrency: 1